import os

SF_USERNAME = os.getenv('SF_USERNAME')
SF_PASSWORD = os.getenv('SF_PASSWORD')
SF_TOKEN = os.getenv('SF_TOKEN')
GCHAT_API_KEY = os.getenv('GCHAT_API_KEY')
GCHAT_TOKEN = os.getenv('GCHAT_TOKEN')

CALLBACK_ACCOUNT_ID = '00G0d000003WBGaEAO'
FLEET_ACCOUNT_ID = '00G320000037CgyEAE'
CLOUD_ACCOUNT_ID = '00G0d0000036BHlEAM'
OVERDUE_ACCOUNT_ID = '00G32000003GXSKEA4'
STANDARD_ACCOUNT_ID = '00G32000002swrIEAQ'

BOT_MESSAGE_TEMPLATE = "*Case Number*: {}\n*Priority*: {}\n\n*Subject*: {}\n*Description*: {}"
